-- MySQL Script generated by MySQL Workbench
-- Sat Oct 26 17:47:31 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `comp344ass2` DEFAULT CHARACTER SET utf8 ;
USE `comp344ass2` ;

-- -----------------------------------------------------
-- Table `comp344ass2`.`DeveliveryCompany`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comp344ass2`.`DeveliveryCompany` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comp344ass2`.`Shipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comp344ass2`.`Shipment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Shopper_id` INT NOT NULL,
  `Shaddr_id` INT NOT NULL,
  `Delivery_Company_id` INT NOT NULL,
  `picked_up_at` DATETIME NULL,
  `expected_delivery_date` DATETIME NULL,
  `shopper_notified` TINYINT NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Shipment_DeveliveryCompany1_idx` (`Delivery_Company_id` ASC) ,
  CONSTRAINT `fk_Shipment_DeveliveryCompany1`
    FOREIGN KEY (`Delivery_Company_id`)
    REFERENCES `comp344ass2`.`DeveliveryCompany` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comp344ass2`.`ShipmentItems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comp344ass2`.`ShipmentItems` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Shipment_id` INT NOT NULL,
  `Order_id` INT NOT NULL,
  `Order_Product_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ShipmentItems_Shipment1_idx` (`Shipment_id` ASC) ,
  CONSTRAINT `fk_ShipmentItems_Shipment1`
    FOREIGN KEY (`Shipment_id`)
    REFERENCES `comp344ass2`.`Shipment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO `comp344ass2`.`shipment`
(`id`,
`Shopper_id`,
`Shaddr_id`,
`Delivery_Company_id`,
`picked_up_at`,
`expected_delivery_date`,
`shopper_notified`,
`status`)
VALUES
(1,
1,
1,
1,
NOW(),
NOW(),
1,
'not_shipped');
SELECT * FROM `comp344ass2`.shipment;

INSERT INTO `comp344ass2`.`shipment`
(`id`,
`Shopper_id`,
`Shaddr_id`,
`Delivery_Company_id`,
`picked_up_at`,
`expected_delivery_date`,
`shopper_notified`,
`status`)
VALUES
(2,
2,
2,
2,
NOW(),
NOW(),
1,
'not_shipped');
SELECT * FROM `comp344ass2`.shipment;

INSERT INTO `comp344ass2`.`shipment`
(`id`,
`Shopper_id`,
`Shaddr_id`,
`Delivery_Company_id`,
`picked_up_at`,
`expected_delivery_date`,
`shopper_notified`,
`status`)
VALUES
(3,
3,
3,
3,
NOW(),
NOW(),
1,
'not_shipped');
SELECT * FROM `comp344ass2`.shipment;
